### PR TITLE
Task/24 matching paper details

### PR DESCRIPTION
**Pull request by nonsensenv**
- #24
- #68 
## Problem
- results page search bar overflow
- no matching paper details

> added matching paper details

> Specific webpage ttile that matches the selected research title (unlike before its just "localhost:3000")
_Note: yet this still only applied to the matching paper details page_

### CODE REVIEW

**Review by Techies-John — APPROVED** [review]
Final review 1.0.9

**Comment by Techies-John** [comment]
image

**Comment by Techies-John** [comment]
image

**Review by sggenDebugs — APPROVED** [review]
very good approved

**Comment by sggenDebugs** [comment]
Also search bar still overflows. Create a pr for this thank you.
image

**Pull request merged**
