### PR TITLE
Task/72 filter dropdown

### PR DESCRIPTION
**Pull request by whiteNsky**
#72 

- Added Filter Dropdown

### CODE REVIEW

**Review by Techies-John — DISMISSED** [review]
Final final review 1.0.9

**Comment by Techies-John** [comment]
100000000000000000000000000000000 business days

**Comment by Techies-John** [comment]
image

**Review by Techies-John — DISMISSED** [review]

**Review by sggenDebugs — DISMISSED** [review]
approved

**Review by sggenDebugs — APPROVED** [review]

**Pull request merged**
